modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
logoFile = "icon.png"
[[mods]]
modId = "elake_tech"
version = "0.0.1"
displayName = "Elake Tech"
displayURL = "https://www.elake.top"
authors = "Erhai-lake & Qi-Month"
description = '''Elake Tech'''
[[mixins]]
config = "elake_tech.mixins.json"
[[dependencies."elake_tech"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."elake_tech"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"